//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjToolist
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FUENMLEntities : DbContext
    {
        public FUENMLEntities()
            : base("name=FUENMLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<place> places { get; set; }
        public virtual DbSet<placeList> placeLists { get; set; }
        public virtual DbSet<placeRelation> placeRelations { get; set; }
        public virtual DbSet<tag> tags { get; set; }
        public virtual DbSet<tagEvent> tagEvents { get; set; }
        public virtual DbSet<tagRelation> tagRelations { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
